#!/usr/bin/env python3
import random

wordbank= ["indentation", "spaces"] 
tlgstudents= ['Albert', 'Anthony', 'Brenden', 'Craig', 'Deja', 'Elihu', 'Eric', 'Giovanni', 'James', 'Joshua', 'Maria', 'Mohamed', 'PJ', 'Philip', 'Sagan', 'Suchit', 'Meka', 'Trey', 'Winton', 'Xiuxiang', 'Yaping']
wordbank.append(4)

num = input("what's your favorite number between 0 and 20?\n>")
intnum = int(num)

student_name = tlgstudents[intnum]
student_name2 = random.choice(tlgstudents)

listnum = len(tlgstudents)
stunum = int(input("what's the student number you like to go that is larger than 0?"))-1
print(stunum)

print(f"{student_name2} always uses {wordbank[-1]} {wordbank[1]} to indent.")

print(f"{student_name} always uses {wordbank[-1]} {wordbank[1]} to indent.")

car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.keys()
print(x)
y = list(x)
print(y[2])
